### ISSUE TITLE
怎么才能获取到选中的值

### ISSUE THREAD

**Issue by LeeDawson** [weijhfly/jqueryDatePlugin#1]
有demo吗

**Comment by weijhfly** [comment]
我不太明白获取选中的值是什么意思，具体是指点击确定后的日期吗？如果是这样的话，你可以用事件委托监听确定按钮的click事件，然后去获取绑定插件元素的value或者text值。

**Comment by weijhfly** [comment]
上面这种情况是选择了日期后，必须去执行某个操作，如果不是要及时的获取日期，可以用类似$('#date').val()或者$('#date').text()来获取(取决于是input还是其他的dom元素)，另外如果可以，希望能给个star吧。
