### ISSUE TITLE
您好怎么就是选中时间了，当我在选择时间的时候是我选择的那个时间

### ISSUE THREAD

**Issue by likang329** [weijhfly/jqueryDatePlugin#2]
您好我在用您这个插件的时候遇见了一个问题，目前项目需要选择了一个时间段，然后在选择时间的时候需要定位的时间不是当前的时间还是之前选择的时间段，请问怎么解决

**Comment by weijhfly** [comment]
刚刚就你这个问题在github上发了一版，请下载试试，示例见demo.html。

**Comment by likang329** [comment]
可以了，万分感谢，希望您能越做越好^_^

**Comment by weijhfly** [comment]
哈哈，没啥，也喜欢折腾

**Comment by likang329** [comment]
大神貌似在ios有点问题，ios还是选择的当前的时间，安卓是没问题...

**Comment by weijhfly** [comment]
应该不会有区别，我用https://weijhfly.github.io/date-demo.html 测试跳转没问题，请看214至222行js，代码很简单，你可以调试试试，不过也有可能是兼容性问题。
