### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by chenguojun** [weijhfly/jqueryDatePlugin#4]
点击确认按钮有时会报错，显示确认按钮的d-id参数没有成功复制，即$('#d-confirm').attr('d-id', obj); 这一句有时会失效
放在that.bind('click',function() {
    $('#d-confirm').attr('d-id', obj);
    ....................
}
反而没报错，希望能看一下是什么问题

**Comment by weijhfly** [comment]
从来没发现这个情况，这里只是简单的记录一下css选择器而已，可以按照你说的挪到第一行。

**Comment by wlpgdq** [comment]
在angular.js的controller中定义调用的回调函数，报错，是不是因为回调函数必须是全局函数，应该怎么解决呢？

**Comment by weijhfly** [comment]
@wlpgdq 旧版的确实必须是全局函数，在window下面的才行，此版设计不够合理，你看能否使用新版https://github.com/weijhfly/rolldate

**Comment by wlpgdq** [comment]
好的，谢谢
